### PR TITLE
Frontend UI Updates, Authentication Integration, and Backend Authentication Refactoring

### PR DESCRIPTION
**Pull request by jonathan-githubofficial**
**Main Contributors:**
@jonathan-githubofficial
@mathieutrudeau
@usamasaleem1
@Radwanbaba13
@sFranchetto
@Ahed752
@mubashir494
Key Activities:

**Frontend Enhancements:**
Development and optimization of new components:
Player and PlayerBar creation.
Introduction of the Player Page and Main Page.
Significant contributions to the user profile page, incorporating component structuring and styling.
Enhancing site responsiveness for an improved user experience.
Revamping and cleaning up the navigation bar.
Integrating Single Sign-On (SSO), with a focus on Google SSO.

**Backend Refinements:**
Comprehensive backend optimizations, with a focus on decoupling and testing.
Establishment of a continuous integration environment, notably for end-to-end (E2E) testing.
In-depth authentication updates, as seen with AuthTests and the AuthController.
Dockerfile amendments and meticulous dependency management.

### CODE REVIEW

**Comment by BigSaladMan** [comment]
can you rename the PR to something else? Kinda cursed the way it is right now. Need the issue in the title plus give a small summary of what this is

**Review by mathieutrudeau — APPROVED** [review]

**Comment by mathieutrudeau** [comment]
# Use Case Diagrams for #6 , #11  and #2 

Iteration 2 Use Cases drawio (1)

**Review by Radwanbaba13 — APPROVED** [review]
All Tests Passed, works good

**Comment by usamasaleem1** [comment]
LGTM

**Review by shadijiha — APPROVED** [review]
Backend stuff is good

**Review by usamasaleem1 — APPROVED** [review]

**Pull request merged**
